# GET http://localhost:7071/api/meetings/join
POST http://localhost:7071/api/meetings/clear

{
    "devlock": "meow"
}

###

POST https://sep-nojo-test.azurewebsites.net/api/meetings/clear

{
    "devlock": "meow"
}