# POST http://localhost:7071/api/todos
POST http://localhost:7071/api/meetings

{
    "meetingName": "Example Meeting",
    "creatorName": "Nojo"
}

###

POST https://sep-nojo-test.azurewebsites.net/api/meetings

{
    "meetingName": "Meow Deow's Meeting",
    "creatorName": "Me"
}