# POST http://localhost:7071/api/meetings/join
POST http://localhost:7071/api/meetings/join

{
    "meetingId": "628b61f1a61e94b859575a8b",
    "memberName": "Nojo"
}


###

POST https://sep-nojo-test.azurewebsites.net/api/meetings/join

{
    "meetingId": "628b61f1a61e94b859575a8b",
    "memberName": "Nojo"
}