# POST http://localhost:7071/api/meetings/join
POST http://localhost:7071/api/meetings/leave

{
    "meetingId": "62b075005386c6afbf17be19",
    "memberId": "62b075530566f8a6c08b1bc2"
}

###

POST https://sep-nojo-test.azurewebsites.net/api/meetings/leave

{
    "meetingId": "628b61f1a61e94b859575a8b",
    "memberId": "Nojo"
}