POST http://localhost:7071/api/notifications

{
    "meetingId": "62b075005386c6afbf17be19",
    "receiverId": "62b075135386c6afbf17be1a",
    "message": "Kuchen uwu"
}

###

POST https://sep-nojo-test.azurewebsites.net/api/notifications

{
    "meetingId": "62b075005386c6afbf17be19",
    "receiverId": "62b075135386c6afbf17be1a",
    "message": "Kuchen uwu"
}