POST http://localhost:7071/api/notifications

{
    "meetingId": "62a740700b2f37e088c34deb",
    "receiverId": "62a740700b2f37e088c34dea",
    "message": "Kuchen uwu"
}

###

POST https://sep-nojo-test.azurewebsites.net/api/notifications

{
    "meetingId": "629625f06218d4201eb4a1fd",
    "creatorId": "629625f06218d4201eb4a1fe"
}
