POST http://localhost:7071/api/notifications/delete

{
    "meetingId": "62b075005386c6afbf17be19",
    "receiverId": "62b075135386c6afbf17be1a",
    "notificationId": "62b075950566f8a6c08b1bc3"
}

###

POST https://sep-nojo-test.azurewebsites.net/api/notifications/delete

{
    "meetingId": "629625f06218d4201eb4a1fd",
    "memberId": "629625f06218d4201eb4a1fe",
    "notificationId": "629625f06218d4201eb4a1ff",
}
