# POST http://localhost:7071/api/todos

POST http://localhost:7071/api/sixhats/stop

{
    "meetingId": "62b07aecbbb8e4e361ddf639"
}

###
POST https://sep-nojo-test.azurewebsites.net/api/sixhats/stop

{
    "meetingId": "6294b371dd7aa23a8a41fcd2"
}