# POST http://localhost:7071/api/todos

POST http://localhost:7071/api/tools

{
    "meetingId": "629625f06218d4201eb4a1fd",
    "toolType": "devils_advocat"
}

### Azure Deployment
### member list no longer required
### for full specs see api documentation

POST https://sep-nojo-test.azurewebsites.net/api/tools

{
    "meetingId": "6294ad903327a79e34c33f0b",
    "toolType": "devils_advocat"
}