POST http://localhost:7071/api/surveys

{
    "meetingId": "62b07aecbbb8e4e361ddf639",
    "question": "This is an example question. What do you think?",
    "creatorName": "Nojo",
    "choices": [
        "Y e s",
        "No",
        "Absolutely not",
        "Sure..?"
    ]
}

### Azure Deployment

POST https://sep-nojo-test.azurewebsites.net/api/surveys

{
    "meetingId": "62a707677939ed0a34c324b2",
    "question": "This is an example question. What do you think?",
    "creatorName": "Nojo",
    "choices": [
        "Y e s",
        "No",
        "Absolutely not",
        "Sure..?"
    ]
}