POST http://localhost:7071/api/surveys/answers

{
    "meetingId": "62b07aecbbb8e4e361ddf639",
    "surveyId": "62b07afdbbb8e4e361ddf63b",
    "answers": [
        {
            "memberName": "Nojo",
            "answer": "Custom Text"
        },
        {
            "memberName": "Nojo",
            "answer": "Choice 1 from UI"
        }
    ]
}

### Azure Deployment

POST https://sep-nojo-test.azurewebsites.net/api/surveys/answers

{
    "meetingId": "62a707677939ed0a34c324b2",
    "surveyId": "todo: objectid einfügen",
    "answers": [
        {
            "memberName": "Nojo",
            "answer": "Custom Text"
        },
        {
            "memberName": "Nojo",
            "answer": "Choice 1 from UI"
        }
    ]
}